# source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
inhibit_all_warnings!
platform :osx, '10.13'

target 'IMProcessingXmp-Pod' do
    inherit! :search_paths
    
    #
    # develop ode
    #
    pod 'IMProcessingXMP', :path => '../../'
    
    #
    # release
    #
    # pod 'IMProcessingXMP', :git => 'https://github.com/dehancer/IMProcessingXMP'
    pod 'SnapKit'
    
end
